### ISSUE TITLE
Connection is timing out waiting for XRP paychan to be created

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/amundsen#23]
```sh
moneyd git:master ❯ DEBUG=ilp* moneyd start -c ~/.moneyd/config-test.json                                                                                ⏎ ✹
                                                                           88
                                                                           88
                                                                           88
88,dPYba,,adPYba,   ,adPPYba,  8b,dPPYba,   ,adPPYba, 8b       d8  ,adPPYb,88
88P'   "88"    "8a a8"     "8a 88P'   `"8a a8P_____88 `8b     d8' a8"    `Y88
88      88      88 8b       d8 88       88 8PP"""""""  `8b   d8'  8b       88
88      88      88 "8a,   ,a8" 88       88 "8b,   ,aa   `8b,d8'   "8a,   ,d88
88      88      88  `"YbbdP"'  88       88  `"Ybbd8"'     Y88'     `"8bbdP"Y8
                                                          d8'
                                                         d8'
set environment; starting moneyd
2018-02-07T21:54:38.710Z connector:accounts info add account. accountId=parent
2018-02-07T21:54:39.281Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-02-07T21:54:39.284Z connector:accounts info add account. accountId=local
2018-02-07T21:54:39.289Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=local
2018-02-07T21:54:39.289Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-07T21:54:39.290Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-07T21:54:39.296Z ilp-plugin-btp debug registering data handler
2018-02-07T21:54:39.297Z ilp-plugin-btp debug registering money handler
2018-02-07T21:54:39.297Z ilp-plugin-btp debug registering data handler
2018-02-07T21:54:39.298Z ilp-plugin-btp debug registering money handler
2018-02-07T21:54:39.512Z ilp-plugin-btp debug connected to server
2018-02-07T21:54:39.723Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":1080102174,"data":{"protocolData":[]}}
2018-02-07T21:54:39.724Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 1080102174): {"protocolData":[]}
2018-02-07T21:54:39.762Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":247603438,"data":{"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,99,104,97,110,110,101,108,34,58,34,56,68,55,68,70,56,56,66,70,70,57,69,57,49,69,67,50,66,67,53,67,69,55,55,55,51,55,51,70,48,51,50,52,51,57,54,65,68,51,65,66,69,65,67,53,52,68,53,49,68,52,52,48,54,68,49,56,53,53,57,70,66,65,52,34,44,34,97,100,100,114,101,115,115,34,58,34,114,71,113,100,76,53,87,105,81,109,52,67,115,114,56,53,103,77,66,70,113,66,67,83,120,103,107,54,71,87,116,51,103,53,34,44,34,97,99,99,111,117,110,116,34,58,34,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,98,52,77,106,116,69,121,98,75,70,89,111,53,112,84,95,114,81,97,67,111,90,113,121,111,111,103,54,86,88,86,88,48,109,112,90,89,70,122,107,86,73,56,34,125]}}]}}
2018-02-07T21:54:39.762Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 247603438): {"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,99,104,97,110,110,101,108,34,58,34,56,68,55,68,70,56,56,66,70,70,57,69,57,49,69,67,50,66,67,53,67,69,55,55,55,51,55,51,70,48,51,50,52,51,57,54,65,68,51,65,66,69,65,67,53,52,68,53,49,68,52,52,48,54,68,49,56,53,53,57,70,66,65,52,34,44,34,97,100,100,114,101,115,115,34,58,34,114,71,113,100,76,53,87,105,81,109,52,67,115,114,56,53,103,77,66,70,113,66,67,83,120,103,107,54,71,87,116,51,103,53,34,44,34,97,99,99,111,117,110,116,34,58,34,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,98,52,77,106,116,69,121,98,75,70,89,111,53,112,84,95,114,81,97,67,111,90,113,121,111,111,103,54,86,88,86,88,48,109,112,90,89,70,122,107,86,73,56,34,125]}}]}
2018-02-07T21:54:39.763Z ilp-plugin-xrp-asym-client debug got info: { channel: '8D7DF88BFF9E91EC2BC5CE777373F0324396AD3ABEAC54D51D4406D18559FBA4',
  address: 'rGqdL5WiQm4Csr85gMBFqBCSxgk6GWt3g5',
  account: 'test.amundsen.bmp.btp18q1.b4MjtEybKFYo5pT_rQaCoZqyoog6VXVX0mpZYFzkVI8' }
2018-02-07T21:54:40.705Z ilp-plugin-xrp-asym-client debug no client channel has been established; requesting
2018-02-07T21:55:15.705Z connector:app error Error: 402427925 timed out
    at Timeout.setTimeout (/usr/local/lib/node_modules/moneyd/node_modules/ilp-plugin-btp/index.js:334:16)
    at ontimeout (timers.js:458:11)
    at tryOnTimeout (timers.js:296:5)
    at Timer.listOnTimeout (timers.js:259:5)

```

**Comment by michielbdejong** [comment]
Hm, it thinks your account exists, seeing it in the logs:
```sh
2018-02-08T11:20:03.132Z ilp-plugin-xrp-server debug auto-claiming. account=b4MjtEybKFYo5pT_rQaCoZqyoog6VXVX0mpZYFzkVI8 amount=0 lastClaimedAmount=0
```
Can you send me your `~/.moneyd.test.json` via Slack, then i can try to connect as your account, see what i can debug.

**Comment by emschwartz** [comment]
I've tried this with a number of new accounts and the same thing happens so you should be able to reproduce just by running:
```sh
moneyd configure -c ~/.moneyd/config-test.json --testnet
DEBUG=ilp* moneyd start -c ~/.moneyd/config-test.json
```

In any case, this is the file (it's fake money anyway):
```json
{
  "secret": "ssJ18dzKuQxL9xv9YnhMoa3L7gtJj",
  "rippled": "wss://s.altnet.rippletest.net:51233",
  "parent": "amundsen.ilpdemo.org:1801",
  "address": "r9YyZyvLiKegmKHZarEVTzeszSH84Qe9Ru"
}
```

**Comment by michielbdejong** [comment]
ok, saw it now:
```sh
2018-02-08T16:52:43.765Z ilp-plugin-xrp-server debug failed to pay account.
            destination=test.amundsen.bmp.btp18q1.6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6-Bs-xVNZqplQw.XmWKc9DrpBs.7bx_LEpRrP2cbcAq2hlQG6de
            error=BigNumber Error: new BigNumber() not a number: undefined
    at raise (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:1191:25)
    at /home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:1179:33
    at new BigNumber (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/node_modules/bignumber.js/bignumber.js:194:67)
    at Account.getOutgoingBalance (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/src/account.js:116:12)
    at Plugin._sendMoneyToAccount (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/index.js:530:36)
    at util._requestId.then (/home/michiel/amundsen/node_modules/ilp-plugin-xrp-asym-server/index.js:508:34)
    at <anonymous>

**Comment by michielbdejong** [comment]
Continued in https://github.com/interledgerjs/ilp-plugin-xrp-asym-server/issues/14

**Comment by emschwartz** [comment]
@michielbdejong what does this issue have to do with https://github.com/michielbdejong/letter-shop/issues/4?

**Comment by michielbdejong** [comment]
sorry, i think there may have been multiple problems. yours, i can't reproduce now, this is what I see:
```sh
DEBUG=ilp* moneyd start -c ~/.moneyd/config-test.json
                                                                           88
                                                                           88
                                                                           88
88,dPYba,,adPYba,   ,adPPYba,  8b,dPPYba,   ,adPPYba, 8b       d8  ,adPPYb,88
88P'   "88"    "8a a8"     "8a 88P'   `"8a a8P_____88 `8b     d8' a8"    `Y88
88      88      88 8b       d8 88       88 8PP"""""""  `8b   d8'  8b       88
88      88      88 "8a,   ,a8" 88       88 "8b,   ,aa   `8b,d8'   "8a,   ,d88
88      88      88  `"YbbdP"'  88       88  `"Ybbd8"'     Y88'     `"8bbdP"Y8
                                                          d8'
                                                         d8'
set environment; starting moneyd
2018-02-08T17:51:14.326Z connector:accounts info add account. accountId=parent
2018-02-08T17:51:14.645Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-02-08T17:51:14.646Z connector:accounts info add account. accountId=local
2018-02-08T17:51:14.649Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=local
2018-02-08T17:51:14.649Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-08T17:51:14.649Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-08T17:51:14.654Z ilp-plugin-btp debug registering data handler
2018-02-08T17:51:14.654Z ilp-plugin-btp debug registering money handler
2018-02-08T17:51:14.654Z ilp-plugin-btp debug registering data handler
2018-02-08T17:51:14.655Z ilp-plugin-btp debug registering money handler
2018-02-08T17:51:15.756Z ilp-plugin-btp debug connected to server
2018-02-08T17:51:16.184Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":46726057,"data":{"protocolData":[]}}
2018-02-08T17:51:16.184Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 46726057): {"protocolData":[]}
2018-02-08T17:51:16.420Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":2633668524,"data":{"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,99,104,97,110,110,101,108,34,58,34,55,54,49,57,56,65,68,56,54,66,53,69,66,69,68,65,67,67,66,68,48,51,57,52,70,67,67,57,55,67,70,55,50,48,68,69,66,67,50,54,66,66,50,67,53,56,55,67,55,52,52,56,67,51,68,48,48,50,49,68,54,50,65,67,34,44,34,97,100,100,114,101,115,115,34,58,34,114,71,113,100,76,53,87,105,81,109,52,67,115,114,56,53,103,77,66,70,113,66,67,83,120,103,107,54,71,87,116,51,103,53,34,44,34,97,99,99,111,117,110,116,34,58,34,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,109,105,102,97,53,85,66,109,66,77,56,100,79,105,80,108,97,84,67,115,118,82,52,112,97,97,51,51,53,56,51,105,122,50,118,80,102,115,95,67,53,66,107,34,125]}}]}}
2018-02-08T17:51:16.420Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 2633668524): {"protocolData":[{"protocolName":"info","contentType":2,"data":{"type":"Buffer","data":[123,34,99,104,97,110,110,101,108,34,58,34,55,54,49,57,56,65,68,56,54,66,53,69,66,69,68,65,67,67,66,68,48,51,57,52,70,67,67,57,55,67,70,55,50,48,68,69,66,67,50,54,66,66,50,67,53,56,55,67,55,52,52,56,67,51,68,48,48,50,49,68,54,50,65,67,34,44,34,97,100,100,114,101,115,115,34,58,34,114,71,113,100,76,53,87,105,81,109,52,67,115,114,56,53,103,77,66,70,113,66,67,83,120,103,107,54,71,87,116,51,103,53,34,44,34,97,99,99,111,117,110,116,34,58,34,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,109,105,102,97,53,85,66,109,66,77,56,100,79,105,80,108,97,84,67,115,118,82,52,112,97,97,51,51,53,56,51,105,122,50,118,80,102,115,95,67,53,66,107,34,125]}}]}
2018-02-08T17:51:16.421Z ilp-plugin-xrp-asym-client debug got info: { channel: '76198AD86B5EBEDACCBD0394FCC97CF720DEBC26BB2C587C7448C3D0021D62AC',
  address: 'rGqdL5WiQm4Csr85gMBFqBCSxgk6GWt3g5',
  account: 'test.amundsen.bmp.btp18q1.mifa5UBmBM8dOiPlaTCsvR4paa33583iz2vPfs_C5Bk' }
2018-02-08T17:51:20.519Z ilp-plugin-xrp-asym-client debug no client channel has been established; requesting
2018-02-08T17:51:24.982Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":3197955619,"data":{"protocolData":[{"protocolName":"fund_channel","contentType":0,"data":{"type":"Buffer","data":[81,20,112,102,49,146,154,98,235,171,207,198,84,52,125,169,244,42,120,73,121,235,204,179,45,87,199,233,154,116,40,178]}}]}}
2018-02-08T17:51:24.983Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 3197955619): {"protocolData":[{"protocolName":"fund_channel","contentType":0,"data":{"type":"Buffer","data":[81,20,112,102,49,146,154,98,235,171,207,198,84,52,125,169,244,42,120,73,121,235,204,179,45,87,199,233,154,116,40,178]}}]}
2018-02-08T17:51:25.322Z ilp-plugin-xrp-asym-client debug setting claim interval on channel.
2018-02-08T17:51:25.322Z ilp-plugin-xrp-asym-client debug loaded best claim of { amount: '0' }
2018-02-08T17:51:25.323Z ilp-plugin-xrp-asym-client debug connected asym client plugin
2018-02-08T17:51:25.567Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":1896992478,"data":{"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[13,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,69,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,109,105,102,97,53,85,66,109,66,77,56,100,79,105,80,108,97,84,67,115,118,82,52,112,97,97,51,51,53,56,51,105,122,50,118,80,102,115,95,67,53,66,107,6,3,88,82,80]}}]}}
2018-02-08T17:51:25.568Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 1896992478): {"protocolData":[{"protocolName":"ilp","contentType":0,"data":{"type":"Buffer","data":[13,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,75,69,116,101,115,116,46,97,109,117,110,100,115,101,110,46,98,109,112,46,98,116,112,49,56,113,49,46,109,105,102,97,53,85,66,109,66,77,56,100,79,105,80,108,97,84,67,115,118,82,52,112,97,97,51,51,53,56,51,105,122,50,118,80,102,115,95,67,53,66,107,6,3,88,82,80]}}]}
2018-02-08T17:51:25.569Z ilp-protocol-ildcp debug received client info. clientAddress=test.amundsen.bmp.btp18q1.mifa5UBmBM8dOiPlaTCsvR4paa33583iz2vPfs_C5Bk assetScale=6 assetCode=XRP
2018-02-08T17:51:25.569Z connector:accounts info setting ilp address. oldAddress=unknown newAddress=test.amundsen.bmp.btp18q1.mifa5UBmBM8dOiPlaTCsvR4paa33583iz2vPfs_C5Bk
2018-02-08T17:51:25.573Z ilp-protocol-ildcp debug received client info. clientAddress=test.amundsen.bmp.btp18q1.mifa5UBmBM8dOiPlaTCsvR4paa33583iz2vPfs_C5Bk.local assetScale=6 assetCode=XRP
2018-02-08T17:51:25.573Z ilp-plugin-mini-accounts debug listening on port 7768
2018-02-08T17:51:25.577Z connector:app info connector ready (republic attitude). address=test.amundsen.bmp.btp18q1.mifa5UBmBM8dOiPlaTCsvR4paa33583iz2vPfs_C5Bk
2018-02-08T17:51:25.814Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":3263635928,"data":{"protocolData":[{"protocolName":"last_claim","contentType":2,"data":{"type":"Buffer","data":[123,34,97,109,111,117,110,116,34,58,34,48,34,125]}}]}}
2018-02-08T17:51:25.814Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 3263635928): {"protocolData":[{"protocolName":"last_claim","contentType":2,"data":{"type":"Buffer","data":[123,34,97,109,111,117,110,116,34,58,34,48,34,125]}}]}
2018-02-08T17:51:25.814Z ilp-plugin-xrp-asym-client debug given last claim of { amount: '0' }
2018-02-08T17:51:25.815Z ilp-plugin-xrp-asym-client debug signing first claim
2018-02-08T17:51:26.119Z ilp-xrp-channel-watcher debug watching paychan 5114706631929A62EBABCFC654347DA9F42A784979EBCCB32D57C7E99A7428B2
2018-02-08T17:51:26.119Z ilp-plugin-btp debug processing btp packet {"type":1,"requestId":3958509740,"data":{"protocolData":[]}}
2018-02-08T17:51:26.119Z ilp-plugin-btp debug received BTP packet (TYPE_RESPONSE, RequestId: 3958509740): {"protocolData":[]}
```

Can you try again?

**Comment by emschwartz** [comment]
Just tried it again with the same result. It times out waiting for amundsen to create a channel to it

The new config file is:
```json
{
  "secret": "shbXnQjAbd8bLPdQLdYVSRYJ6aLCx",
  "rippled": "wss://s.altnet.rippletest.net:51233",
  "parent": "amundsen.ilpdemo.org:1801",
  "address": "rnSVtCy88gSQJr4er41yoGwsvUcL855wiY"
}
```

**Comment by michielbdejong** [comment]
I can't replicate your issue, sorry. I tried both with the `moneyd configure` command you gave and with the config file you gave. What could be different between your laptop and mine?

**Comment by michielbdejong** [comment]
Can you try to cd into a checkout of the moneyd repo, get the latest master, then npm install and `node ./bin/index.js start -c ~/.moneyd/config-test.json`

**Comment by michielbdejong** [comment]
also, can you test `curl -i https://amundsen.ilpdemo.org:1801/`, it should give something like:
```sh
HTTP/1.1 200 OK
Date: Thu, 08 Feb 2018 18:39:26 GMT
Connection: keep-alive
Content-Length: 69

CF01test.amundsen.bmp,invalid packet type received. type=undefined[

**Comment by emschwartz** [comment]
Ok that worked. I was on moneyd v2.2.1, maybe that was the problem 🤔
